// SPDX-License-Identifier: Apache-2.0

package exit

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/a-holm/messq/internal/wirecode"
)

var update = flag.Bool("update", false, "rewrite docs/generated/exit-codes.md")

const generatedDoc = "../../../docs/generated/exit-codes.md"

// renderGeneratedDoc builds the operator-facing exit-code table straight from this
// package's data: the contract prose cannot drift from the classifier because there
// is only one table and the doc is generated from it.
func renderGeneratedDoc() string {
	var b strings.Builder
	fmt.Fprint(&b, "<!-- Generated by `go test ./internal/cli/exit -update`. Do not edit. -->\n\n")
	fmt.Fprint(&b, "# Exit codes\n\n")
	fmt.Fprint(&b, "Every messq command exits 0–7 per PLAN.md section 8. Two documented\n")
	fmt.Fprint(&b, "exceptions sit outside the table: `messq serve` keeps its sysexits values\n")
	fmt.Fprint(&b, "`74` (storage latch), `75` (data dir locked) and `78` (config will never\n")
	fmt.Fprint(&b, "work) for systemd's `RestartPreventExitStatus`, and an interrupt exits\n")
	fmt.Fprint(&b, "`130` (128+SIGINT).\n\n")

	codes := make([]int, 0, len(names))
	for c := range names {
		codes = append(codes, c)
	}
	sort.Ints(codes)
	fmt.Fprint(&b, "| Exit | Name | Meaning |\n|---|---|---|\n")
	for _, c := range codes {
		meaning := map[int]string{
			OK:          "success",
			Error:       "generic runtime failure, incl. a bug in the daemon",
			Usage:       "bad flag, bad argument, request the daemon rejected as malformed",
			NotFound:    "stream / consumer / message / seq does not exist",
			Conflict:    "conflict, stale fence, precondition or limit refused the request",
			Empty:       "a wait expired before the request was satisfied (zero rows is still 0)",
			Unreachable: "no answer obtainable from the daemon",
			Denied:      "authentication or authorization refused",
		}[c]
		fmt.Fprintf(&b, "| %d | `%s` | %s |\n", c, names[c], meaning)
	}

	fmt.Fprint(&b, "\n## Wire-code mapping\n\n")
	wire := make([]string, 0, len(ByWireCode))
	for code := range ByWireCode {
		wire = append(wire, string(code))
	}
	sort.Strings(wire)
	fmt.Fprint(&b, "| Wire code | Exit | Name |\n|---|---|---|\n")
	for _, w := range wire {
		e := ByWireCode[wirecode.Code(w)]
		fmt.Fprintf(&b, "| `%s` | %d | `%s` |\n", w, e, Name(e))
	}

	fmt.Fprint(&b, "\n## Daemon sentinel mapping (internal/errs)\n\n")
	sent := make([]string, 0, len(BySentinel))
	for s := range BySentinel {
		sent = append(sent, s.Error())
	}
	sort.Strings(sent)
	fmt.Fprint(&b, "| Sentinel | Exit | Name |\n|---|---|---|\n")
	for _, msg := range sent {
		for s, e := range BySentinel {
			if s.Error() == msg {
				fmt.Fprintf(&b, "| `%s` | %d | `%s` |\n", msg, e, Name(e))
				break
			}
		}
	}
	return b.String()
}

// TestGeneratedExitCodesDocIsCurrent fails when the checked-in document differs from
// what the tables generate; -update rewrites it. CI drift-fails here exactly like
// #3's subject-rules gate.
func TestGeneratedExitCodesDocIsCurrent(t *testing.T) {
	want := renderGeneratedDoc()
	if *update {
		if err := os.WriteFile(generatedDoc, []byte(want), 0o644); err != nil {
			t.Fatalf("write %s: %v", generatedDoc, err)
		}
		return
	}
	got, err := os.ReadFile(generatedDoc)
	if err != nil {
		t.Fatalf("read %s: %v (run `go test ./internal/cli/exit -update`)", generatedDoc, err)
	}
	if string(got) != want {
		t.Fatalf("%s drifted from the exit tables; regenerate with `go test ./internal/cli/exit -update`",
			generatedDoc)
	}
}
