// SPDX-License-Identifier: Apache-2.0

package exit

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/a-holm/messq/internal/wirecode"
)

var update = flag.Bool("update", false, "rewrite docs/generated/exit-codes.md")

const generatedDoc = "../../../docs/generated/exit-codes.md"

// renderGeneratedDoc builds the operator-facing exit-code table straight from this
// package's data: the contract prose cannot drift from the classifier because there
// is only one table and the doc is generated from it.
func renderGeneratedDoc() string {
	var b strings.Builder
	fmt.Fprint(&b, "<!-- Generated by `go test ./internal/cli/exit -update`. Do not edit. -->\n\n")
	fmt.Fprint(&b, "# Exit codes\n\n")
	fmt.Fprint(&b, "Every messq command exits 0–7 per PLAN.md section 8. Two documented\n")
	fmt.Fprint(&b, "exceptions sit outside the table: `messq serve` keeps its sysexits values\n")
	fmt.Fprint(&b, "`74` (storage latch), `75` (data dir locked) and `78` (config will never\n")
	fmt.Fprint(&b, "work) for systemd's `RestartPreventExitStatus`, and an interrupt exits\n")
	fmt.Fprint(&b, "`130` (128+SIGINT).\n\n")

	codes := make([]int, 0, len(names))
	for c := range names {
		codes = append(codes, c)
	}
	sort.Ints(codes)
	fmt.Fprint(&b, "| Exit | Name | Meaning |\n|---|---|---|\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "| %d | `%s` | %s |\n", c, names[c], meanings[c])
	}

	fmt.Fprint(&b, "\n## Wire-code mapping\n\n")
	wire := make([]string, 0, len(ByWireCode))
	for code := range ByWireCode {
		wire = append(wire, string(code))
	}
	sort.Strings(wire)
	fmt.Fprint(&b, "| Wire code | Exit | Name |\n|---|---|---|\n")
	for _, w := range wire {
		e := ByWireCode[wirecode.Code(w)]
		fmt.Fprintf(&b, "| `%s` | %d | `%s` |\n", w, e, Name(e))
	}

	fmt.Fprint(&b, "\n## Daemon sentinel mapping (internal/errs)\n\n")
	sent := make([]string, 0, len(BySentinel))
	for s := range BySentinel {
		sent = append(sent, s.Error())
	}
	sort.Strings(sent)
	fmt.Fprint(&b, "| Sentinel | Exit | Name |\n|---|---|---|\n")
	for _, msg := range sent {
		for s, e := range BySentinel {
			if s.Error() == msg {
				fmt.Fprintf(&b, "| `%s` | %d | `%s` |\n", msg, e, Name(e))
				break
			}
		}
	}
	return b.String()
}

// recoverDocumented runs Documented and returns its panic message, or "" when it
// returned normally. The half-row guards are the only paths that panic; the empty
// string is therefore the "guard did not fire" answer the tests assert on.
func recoverDocumented() (msg string) {
	defer func() {
		if r := recover(); r != nil {
			msg = fmt.Sprint(r)
		}
	}()
	Documented()
	return ""
}

// TestDocumentedRejectsHalfRow exercises the two panic guards the happy table can
// never reach: a code that carries a name but no meaning, and a meaning that
// references an undocumented code. The tables are package globals, so the tests
// mutate one row, restore it via defer, and never run in parallel — a half row may
// exist only inside the test, never between two calls in the same process.
func TestDocumentedRejectsHalfRow(t *testing.T) {
	t.Run("name without meaning", func(t *testing.T) {
		orig := meanings[OK]
		defer func() { meanings[OK] = orig }()
		delete(meanings, OK)

		msg := recoverDocumented()
		meanings[OK] = orig // restored before the sanity re-check below
		if !strings.Contains(msg, "code 0 has a name but no meaning") {
			t.Fatalf("Documented() with a nameless meaning = %q, want the half-row panic", msg)
		}
		if got := recoverDocumented(); got != "" {
			t.Errorf("Documented() after restoring the table panicked: %q", got)
		}
	})

	t.Run("meaning without code", func(t *testing.T) {
		const ghost = 99 // outside 0–7; nothing in names maps to it
		meanings[ghost] = "a meaning with no documented code"
		defer delete(meanings, ghost)

		msg := recoverDocumented()
		delete(meanings, ghost)
		if !strings.Contains(msg, "a meaning references an undocumented code") {
			t.Fatalf("Documented() with a ghost meaning = %q, want the undocumented-code panic", msg)
		}
		if got := recoverDocumented(); got != "" {
			t.Errorf("Documented() after removing the ghost panicked: %q", got)
		}
	})
}

// TestGeneratedExitCodesDocIsCurrent fails when the checked-in document differs from
// what the tables generate; -update rewrites it. CI drift-fails here exactly like
// #3's subject-rules gate.
func TestGeneratedExitCodesDocIsCurrent(t *testing.T) {
	want := renderGeneratedDoc()
	if *update {
		if err := os.WriteFile(generatedDoc, []byte(want), 0o644); err != nil {
			t.Fatalf("write %s: %v", generatedDoc, err)
		}
		return
	}
	got, err := os.ReadFile(generatedDoc)
	if err != nil {
		t.Fatalf("read %s: %v (run `go test ./internal/cli/exit -update`)", generatedDoc, err)
	}
	if string(got) != want {
		t.Fatalf("%s drifted from the exit tables; regenerate with `go test ./internal/cli/exit -update`",
			generatedDoc)
	}
}
