// SPDX-License-Identifier: Apache-2.0

// Command gendocs generates the CLI reference from the cobra tree (issue #26 §4):
// docs/cli/*.md (GenMarkdownTree), man/man1/messq*.1 (GenManTree, section 1) and
// the man/man8/messq.8 roff include `.so man1/messq.1` that #17's systemd unit
// cites as man:messq(8).
//
// This tool lives in its own Go module so cobra/doc's dependency chain (md2man)
// never spends one of the root module's eight direct-dependency rows of PLAN §13.
// Reproducibility: the man header's Date comes from SOURCE_DATE_EPOCH when set
// (CI and make docs set it to the last commit time), so two builds of one commit
// are byte-identical and `make docs && git diff --exit-code` is a real drift gate.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/a-holm/messq/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	root := flag.String("root", ".", "repository root (the module directory)")
	flag.Parse()
	if err := run(*root); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}
}

// generate runs the generator against out (the test-facing entry point).
func generate(out string) error { return run(out) }

func run(root string) error {
	mdDir := filepath.Join(root, "docs", "cli")
	man1Dir := filepath.Join(root, "man", "man1")
	man8Dir := filepath.Join(root, "man", "man8")
	for _, dir := range []string{mdDir, man1Dir, man8Dir} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	tree := cli.NewRoot(&cli.Env{})

	// The markdown reference: every command, one page, linked.
	prepend := func(filename string) string {
		name := strings.TrimSuffix(filepath.Base(filename), ".md")
		return fmt.Sprintf("<!-- Generated by `make docs` from the command tree. Do not edit. -->\n\n# %s\n\nSee `messq help exit-codes` for the exit-code contract.\n\n", name)
	}
	link := func(name string) string { return name + ".md" }
	if err := doc.GenMarkdownTreeCustom(tree, mdDir, prepend, link); err != nil {
		return fmt.Errorf("markdown tree: %w", err)
	}

	// The man pages, section 1, dated from SOURCE_DATE_EPOCH for reproducibility.
	date := sourceDate()
	header := &doc.GenManHeader{
		Title:   "MESSQ",
		Section: "1",
		Date:    &date,
	}
	if err := doc.GenManTree(tree, header, man1Dir); err != nil {
		return fmt.Errorf("man tree: %w", err)
	}

	// messq(8) is a one-line roff include, never a duplicated page.
	so := ".so man1/messq.1\n"
	if err := os.WriteFile(filepath.Join(man8Dir, "messq.8"), []byte(so), 0o644); err != nil {
		return fmt.Errorf("messq.8: %w", err)
	}
	return nil
}

// sourceDate resolves the reproducibility date: SOURCE_DATE_EPOCH (unix seconds)
// when set, otherwise build time. The Makefile exports SOURCE_DATE_EPOCH from
// the last commit, so one commit renders one date.
func sourceDate() time.Time {
	if s := strings.TrimSpace(os.Getenv("SOURCE_DATE_EPOCH")); s != "" {
		if secs, err := strconv.ParseInt(s, 10, 64); err == nil {
			return time.Unix(secs, 0).UTC()
		}
	}
	return time.Now().UTC()
}

var _ = cobra.Command{}
