// SPDX-License-Identifier: Apache-2.0

package client

import (
	"encoding/json"
	"os"
	"testing"
)

// TestNameGrammarMatchesServerGrammar replays the corpus in
// testdata/name_corpus.json — the verdicts of internal/subject's validators over a
// shared set of names, generated by a scratch test inside that package — through the
// client's mirrored grammar. pkg/client cannot import internals (layers.sh), so this
// committed corpus is the copy-check; regenerate it whenever the S11 grammar moves.
func TestNameGrammarMatchesServerGrammar(t *testing.T) {
	t.Parallel()

	raw, err := os.ReadFile("testdata/name_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var rows []struct {
		Name        string `json:"name"`
		StreamOK    bool   `json:"stream_ok"`
		NewStreamOK bool   `json:"new_stream_ok"`
		ConsumerOK  bool   `json:"consumer_ok"`
	}
	if err := json.Unmarshal(raw, &rows); err != nil {
		t.Fatalf("corpus: %v", err)
	}
	for _, r := range rows {
		if got := validStreamName(r.Name) == nil; got != r.StreamOK {
			t.Errorf("validStreamName(%q) = %v, server says %v", r.Name, got, r.StreamOK)
		}
		if got := validNewStreamName(r.Name) == nil; got != r.NewStreamOK {
			t.Errorf("validNewStreamName(%q) = %v, server says %v", r.Name, got, r.NewStreamOK)
		}
		if got := validConsumerName(r.Name) == nil; got != r.ConsumerOK {
			t.Errorf("validConsumerName(%q) = %v, server says %v", r.Name, got, r.ConsumerOK)
		}
	}
}
